services:
 catalogdb:
  container_name: catalogdb
  environment:
   - POSTGRES_USER=postgres
   - POSTGRES_PASSWORD=postgres
   - POSTGRES_DB=CatalogDb
  restart: always
  ports:
   - "5432:5432"
  volumes:
   - postgres_catalog:/var/lib/postgresql/data/
   
   
 catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Server=catalogdb;port=5432;Database=CatalogDb;User Id=postgres;Password=postgres;Include Error Detail=true
    depends_on:
      - catalogdb
    ports:
      - "6000:8080"
      - "6060:8081"
    volumes:
      - ./secrets/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ./secrets/UserSecrets:/root/.microsoft/usersecrets:ro
      - ./secrets/https:/home/app/.aspnet/https:ro
      - ./secrets/https:/root/.aspnet/https:ro- 
