services:
  catalogdb:
    image: postgres:15
    container_name: catalogdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=CatalogDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_catalog:/var/lib/postgresql/data

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: src/Services/Catalog/Catalog.API
      dockerfile: Dockerfile

volumes:
  postgres_catalog:

